<a href="https://colab.research.google.com/github/fmWaithaka/-Analyzing-Airbnb-Listings-in-Singapore/blob/main/Analyzing_Airbnb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analyzing Airbnb Listings in Singapore

## Data Loading and Exploration
* Download and load both datasets using the Pandas library.
* Explore the first few rows of each dataset to understand their structure and
content

In [1]:
import pandas as pd

# Load the listing data
url = "http://data.insideairbnb.com/singapore/sg/singapore/2023-09-23/data/listings.csv.gz"

# Read the CSV file into a DataFrame
listing_df = pd.read_csv(url)

# Display the first few rows of the DataFrame
listing_df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,71609,https://www.airbnb.com/rooms/71609,20230923135002,2023-09-23,previous scrape,Villa in Singapore · ★4.44 · 2 bedrooms · 3 be...,For 3 rooms.Book room 1&2 and room 4<br /><br ...,NaN,https://a0.muscache.com/pictures/24453191/3580...,367042,...,4.78,4.26,4.32,NaN,f,5,0,5,0,0.14
1,71896,https://www.airbnb.com/rooms/71896,20230923135002,2023-09-23,previous scrape,Home in Singapore · ★4.16 · 1 bedroom · 1 bed ...,<b>The space</b><br />Vocational Stay Deluxe B...,NaN,https://a0.muscache.com/pictures/2440674/ac4f4...,367042,...,4.43,4.17,4.04,NaN,f,5,0,5,0,0.16
2,71903,https://www.airbnb.com/rooms/71903,20230923135002,2023-09-23,previous scrape,Home in Singapore · ★4.41 · 1 bedroom · 2 beds...,"Like your own home, 24hrs access.<br /><br /><...",Quiet and view of the playground with exercise...,https://a0.muscache.com/pictures/568743/7bc623...,367042,...,4.64,4.50,4.36,NaN,f,5,0,5,0,0.31
3,275343,https://www.airbnb.com/rooms/275343,20230923135002,2023-09-23,city scrape,Rental unit in Singapore · ★4.40 · 1 bedroom ·...,**IMPORTANT NOTES: READ BEFORE YOU BOOK! <br ...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,1439258,...,4.42,4.53,4.63,S0399,t,52,1,51,0,0.17
4,275344,https://www.airbnb.com/rooms/275344,20230923135002,2023-09-23,city scrape,Rental unit in Singapore · ★4.27 · 1 bedroom ·...,Lovely home for the special guest !<br /><br /...,Bus stop <br />Food center <br />Supermarket,https://a0.muscache.com/pictures/miso/Hosting-...,1439258,...,4.50,4.63,4.13,S0399,t,52,1,51,0,0.12

In [2]:
# Check the shape
listing_df.shape

(3483, 75)

In [3]:
# Check the columns names
listing_df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'first_review',
       'last_review', 'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [4]:
# Check the info (data type, missing values)
listing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            3483 non-null   int64
 1   listing_url                                   3483 non-null   object
 2   scrape_id                                     3483 non-null   int64
 3   last_scraped                                  3483 non-null   object
 4   source                                        3483 non-null   object
 5   name                                          3483 non-null   object
 6   description                                   3439 non-null   object
 7   neighborhood_overview                         2289 non-null   object
 8   picture_url                                   3483 non-null   object
 9   host_id                                       3483 non-null   int64
 10  host_url                                      3483 non-null   object
 11  host_name                                     3483 non-null   object
 12  host_since                                    3483 non-null   object
 13  host_location                                 2236 non-null   object
 14  host_about                                    2349 non-null   object
 15  host_response_time                            2725 non-null   object
 16  host_response_rate                            2725 non-null   object
 17  host_acceptance_rate                          2560 non-null   object
 18  host_is_superhost                             3294 non-null   object
 19  host_thumbnail_url                            3483 non-null   object
 20  host_picture_url                              3483 non-null   object
 21  host_neighbourhood                            3250 non-null   object
 22  host_listings_count                           3483 non-null   int64
 23  host_total_listings_count                     3483 non-null   int64
 24  host_verifications                            3483 non-null   object
 25  host_has_profile_pic                          3483 non-null   object
 26  host_identity_verified                        3483 non-null   object
 27  neighbourhood                                 2289 non-null   object
 28  neighbourhood_cleansed                        3483 non-null   object
 29  neighbourhood_group_cleansed                  3483 non-null   object
 30  latitude                                      3483 non-null   float64
 31  longitude                                     3483 non-null   float64
 32  property_type                                 3483 non-null   object
 33  room_type                                     3483 non-null   object
 34  accommodates                                  3483 non-null   int64
 35  bathrooms                                     0 non-null      float64
 36  bathrooms_text                                3464 non-null   object
 37  bedrooms                                      1995 non-null   float64
 38  beds                                          3386 non-null   float64
 39  amenities                                     3483 non-null   object
 40  price                                         3483 non-null   object
 41  minimum_nights                                3483 non-null   int64
 42  maximum_nights                                3483 non-null   int64
 43  minimum_minimum_nights                        3483 non-null   int64
 44  maximum_minimum_nights                        3483 non-null   int64
 45  minimum_maximum_nights                        3483 non-null   int64
 46  maximum_maximum_nights                        3483 non-null   int64
 47  minimum_nights_avg_ntm                        3483 non-null   float64
 48  maximum_nights_avg_ntm                        3483 non-null   float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              3483 non-null   object
 51  availability_30                               3483 non-null   int64
 52  availability_60                               3483 non-null   int64
 53  availability_90                               3483 non-null   int64
 54  availability_365                              3483 non-null   int64
 55  calendar_last_scraped                         3483 non-null   object
 56  number_of_reviews                             3483 non-null   int64
 57  number_of_reviews_ltm                         3483 non-null   int64
 58  number_of_reviews_l30d                        3483 non-null   int64
 59  first_review                                  1918 non-null   object
 60  last_review                                   1918 non-null   object
 61  review_scores_rating                          1918 non-null   float64
 62  review_scores_accuracy                        1884 non-null   float64
 63  review_scores_cleanliness                     1884 non-null   float64
 64  review_scores_checkin                         1884 non-null   float64
 65  review_scores_communication                   1885 non-null   float64
 66  review_scores_location                        1884 non-null   float64
 67  review_scores_value                           1884 non-null   float64
 68  license                                       1295 non-null   object
 69  instant_bookable                              3483 non-null   object
 70  calculated_host_listings_count                3483 non-null   int64
 71  calculated_host_listings_count_entire_homes   3483 non-null   int64
 72  calculated_host_listings_count_private_rooms  3483 non-null   int64
 73  calculated_host_listings_count_shared_rooms   3483 non-null   int64
 74  reviews_per_month                             1918 non-null   float64
dtypes: float64(16), int64(23), object(36)
memory usage: 2.0+ MB

In [5]:
listing_df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bathrooms,bedrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,3.483000e+03,3.483000e+03,3.483000e+03,3483.000000,3483.000000,3483.000000,3483.000000,3483.000000,0.0,1995.000000,...,1884.000000,1884.000000,1885.000000,1884.000000,1884.000000,3483.000000,3483.000000,3483.000000,3483.000000,1918.000000
mean,2.607039e+17,2.023092e+13,1.544212e+08,87.198392,145.719495,1.310944,103.843322,2.817112,NaN,1.447118,...,4.497346,4.725648,4.707687,4.691306,4.440632,50.807063,39.910996,10.165662,0.357450,0.558180
std,3.810257e+17,0.000000e+00,1.530722e+08,155.623487,249.134868,0.032431,0.043540,2.199845,NaN,0.747168,...,0.626993,0.508401,0.561206,0.475238,0.632213,72.325185,71.447953,19.831654,1.912801,1.139863
min,7.160900e+04,2.023092e+13,2.366600e+04,1.000000,1.000000,1.221690,103.634572,1.000000,NaN,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.010000
25%,2.476517e+07,2.023092e+13,2.903270e+07,3.000000,5.000000,1.290998,103.834045,2.000000,NaN,1.000000,...,4.270000,4.670000,4.670000,4.570000,4.207500,3.000000,0.000000,0.000000,0.000000,0.050000
50%,4.230188e+07,2.023092e+13,1.075995e+08,14.000000,20.000000,1.304867,103.846020,2.000000,NaN,1.000000,...,4.670000,4.915000,4.920000,4.850000,4.570000,13.000000,1.000000,2.000000,0.000000,0.170000
75%,6.927294e+17,2.023092e+13,2.388916e+08,79.000000,126.000000,1.318060,103.860185,4.000000,NaN,2.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,70.000000,27.000000,9.000000,0.000000,0.627500
max,9.859401e+17,2.023092e+13,5.368571e+08,571.000000,847.000000,1.457802,103.989570,16.000000,NaN,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,253.000000,238.000000,91.000000,18.000000,20.930000

In [6]:
# Check the unique values
listing_df.describe(include=["object", "bool"])

,listing_url,last_scraped,source,name,description,neighborhood_overview,picture_url,host_url,host_name,host_since,...,room_type,bathrooms_text,amenities,price,has_availability,calendar_last_scraped,first_review,last_review,license,instant_bookable
count,3483,3483,3483,3483,3439,2289,3483,3483,3483,3483,...,3483,3464,3483,3483,3483,3483,1918,1918,1295,3483
unique,3483,1,2,1484,2741,1019,3286,915,728,775,...,4,39,2815,577,2,1,1333,1012,105,2
top,https://www.airbnb.com/rooms/71609,2023-09-23,city scrape,Rental unit in Singapore · 1 bedroom · 1 bed ·...,"Located in the heart of Singapore, 36 Club St ...",- Apartment is within lavender neighbourhood (...,https://a0.muscache.com/pictures/miso/Hosting-...,https://www.airbnb.com/users/show/138649185,Apac,2017-07-05,...,Private room,1 bath,"[""Self check-in"", ""Bed linens"", ""Paid parking ...",$49.00,t,2023-09-23,2020-01-01,2023-09-18,Authorised Serviced Apartment,f
freq,1,3483,2701,200,30,73,11,253,253,253,...,1627,1217,50,73,3101,3483,10,26,766,2191

Let's do the same for review data

In [7]:
# Load the review data
url = "http://data.insideairbnb.com/singapore/sg/singapore/2023-09-23/data/reviews.csv.gz"

# Read the CSV file into a DataFrame
review_df = pd.read_csv(url)

# Display the first few rows of the DataFrame
review_df.head()

,listing_id,id,date,reviewer_id,reviewer_name,comments
0,71609,793880,2011-12-19,1456140,Max,The rooms were clean and tidy. Beds very comfo...
1,3209752,523972161,2019-09-05,20987832,Eng Hui,"Thank you for making me feel at home, it is su..."
2,3209752,527054740,2019-09-10,3963956,Lug,"An absolutely amazing place. It’s clean, styli..."
3,3209752,528926785,2019-09-14,66599486,Andrew,This location is private yet it is only 400m w...
4,3209752,538619865,2019-09-30,110050140,Damien,Jeremy is a great host that will make your sta...

In [8]:
review_df.shape

(35698, 6)

In [9]:
review_df.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'comments'], dtype='object')

In [10]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35698 entries, 0 to 35697
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     35698 non-null  int64
 1   id             35698 non-null  int64
 2   date           35698 non-null  object
 3   reviewer_id    35698 non-null  int64
 4   reviewer_name  35698 non-null  object
 5   comments       35691 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.6+ MB

In [11]:
review_df.describe(include=["object"])

              date reviewer_name comments
count        35698         35698    35691
unique        3561         15657    33904
top     2019-09-23         David     Good
freq            46           192      142

## Data Cleaning
* Identify and handle missing data in both datasets. Decide whether to fill
the missing values or drop columns as needed.
* Examine the data types of various columns and assign suitable data types
to each column. Demonstrate the efficiency of these changes by
showcasing the memory usage before and after altering the data types.

In [12]:
# Identify the missing data on the listing_df
missing_values_listings = listing_df.isnull().sum()

missing_values_listings[missing_values_listings > 0]

description                      44
neighborhood_overview          1194
host_location                  1247
host_about                     1134
host_response_time              758
host_response_rate              758
host_acceptance_rate            923
host_is_superhost               189
host_neighbourhood              233
neighbourhood                  1194
bathrooms                      3483
bathrooms_text                   19
bedrooms                       1488
beds                             97
calendar_updated               3483
first_review                   1565
last_review                    1565
review_scores_rating           1565
review_scores_accuracy         1599
review_scores_cleanliness      1599
review_scores_checkin          1599
review_scores_communication    1598
review_scores_location         1599
review_scores_value            1599
license                        2188
reviews_per_month              1565
dtype: int64

In [13]:
#Fill missing values in text columns with "Not available"
text_columns = ['description', 'neighborhood_overview', 'host_location', 'host_about', 'host_neighbourhood', 'neighbourhood', 'bathrooms_text', 'first_review', 'last_review']
listing_df[text_columns] = listing_df[text_columns].fillna("Not available")

In [14]:
# Fill missing values in numerical columns with the mean
numerical_columns = ['bedrooms', 'beds', 'review_scores_rating', 'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 'reviews_per_month']
listing_df[numerical_columns] = listing_df[numerical_columns].fillna(listing_df[numerical_columns].mean())

In [32]:
# Drop the columns High Percentage of Missing Values
columns_to_drop = ['bathrooms', 'calendar_updated', 'license']
listing_df = listing_df.drop(columns=columns_to_drop, axis=1)

KeyError: ignored

In [16]:
# Display unique values in host_response_time and host_response_rate
unique_response_time = listing_df['host_response_time'].unique()
unique_response_rate = listing_df['host_response_rate'].unique()

print("Unique values in host_response_time:")
print(unique_response_time)

print("\nUnique values in host_response_rate:")
print(unique_response_rate)

Unique values in host_response_time:
['within a few hours' 'within an hour' nan 'within a day'
 'a few days or more']

Unique values in host_response_rate:
['100%' '75%' nan '50%' '0%' '82%' '60%' '40%' '57%' '67%' '73%' '93%'
 '89%' '88%' '90%' '95%' '92%' '20%' '94%' '80%' '97%' '33%' '85%' '70%'
 '96%' '98%' '17%' '99%' '10%' '77%' '83%' '86%' '65%' '30%' '78%' '91%'
 '46%' '36%']

Since `host_response_time` is categorical, you can fill missing values with a category that indicates non-response, such as "Not available"

In [22]:
listing_df['host_response_time'].fillna('Not available', inplace=True)

Since `host_response_rate` is numerical, you might consider filling missing values with a specific value (e.g., the mean response rate) or with a distinct value that represents missing data, such as -1.

In [24]:
# Convert 'host_response_rate' to a numerical format (remove '%' sign)
listing_df['host_response_rate'] = listing_df['host_response_rate'].str.rstrip('%').astype('float') / 100.0

# Fill missing values with the mean or another appropriate strategy
listing_df['host_response_rate'].fillna(listing_df['host_response_rate'].mean(), inplace=True)

In [27]:
# Select only the host_response_time and host_response_rate columns
selected_columns = ['host_response_time', 'host_response_rate']
subset_df = listing_df[selected_columns]

# Display the DataFrame with only the selected columns
print(subset_df.head(20))

    host_response_time  host_response_rate
0   within a few hours            1.000000
1   within a few hours            1.000000
2   within a few hours            1.000000
3       within an hour            1.000000
4       within an hour            1.000000
5   within a few hours            1.000000
6   within a few hours            0.750000
7       within an hour            1.000000
8       within an hour            1.000000
9   within a few hours            0.750000
10  within a few hours            0.750000
11       Not available            0.894741
12  within a few hours            1.000000
13       Not available            0.894741
14       Not available            0.894741
15       Not available            0.894741
16        within a day            1.000000
17       Not available            0.894741
18       Not available            0.894741
19       Not available            0.894741

In [29]:
# Display unique values in neighbourhood and host_neighbourhood
unique_neighbourhood = listing_df['neighbourhood'].unique()
unique_host_neighbourhood = listing_df['host_neighbourhood'].unique()

print("Unique values in neighbourhood:")
print(unique_neighbourhood)

print("\nUnique values in host_neighbourhood:")
print(unique_host_neighbourhood)

Unique values in neighbourhood:
['Not available' 'Singapore, Singapore' 'Changi, Singapore'
 'Singapore, Chinatown, Outram, Singapore' 'Orchard , Singapore'
 'Singapore, Bukit Timah, Singapore' 'Singapore, 207557, Singapore'
 'Queensway/Alexandra, Singapore' 'Singapore, SINGAPORE, Singapore'
 'Singapore, NA, Singapore' 'Singapore,   , Singapore'
 'Singapore, Novena, Singapore' 'SINGAPORE, Singapore'
 'Singapore, Jalan Eunos, Singapore' 'West Coast, 新加坡, Singapore'
 'Singapore' 'Singapore, Sg, Singapore' 'Singpapore , Singapore'
 'Singapore , Singapore' 'Tanjong Pagar, Singapore'
 'Woodlands , Singapore' 'Singapore, SG, Singapore' 'Katong, Singapore'
 'Clementi, Singapore' 'Orchard, Singapore' 'Little India, Singapore'
 'Jurong, Singapore' 'n/a, Singapore' 'Singapore, *, Singapore'
 'Novena /Toa Payoh, Singapore' 'Jurong East, Singapore'
 'Potong Pasir, Singapore' 'Jurong East, Singapore , Singapore'
 'Potong Pasir, Singapore , Singapore' 'Farrer Park, Singapore'
 'Singapore, Aljunied, Singapore' 'Novena , Singapore' '新加坡, Singapore'
 'Bugis, Singapore' 'Singapore, 新加坡, Singapore' 'Chinatown, Singapore'
 'Tiong Bahru/Outram Park, Singapore' 'Dhoby Ghaut, Singapore'
 'Lazarus Island, Singapore']

Unique values in host_neighbourhood:
['Tampines' 'Bukit Merah' 'Central Area' 'Serangoon' 'Not available'
 'Bugis/Kampong Glam' 'Kallang' 'Bukit Timah' 'Chinatown' 'Marine Parade'
 'Katong' 'Novena' 'Ang Mo Kio' 'Bukit Batok' 'Arab Street' 'Bedok'
 'Hougang' 'Woodlands' 'Queenstown' 'Orchard' 'Pasir Ris' 'Tanglin'
 'Sembawang' 'Toa Payoh' 'Bishan' 'Geylang' 'Marina Bay' 'River Valley'
 'North Kuta' 'Jurong East' 'Jurong West' 'Sengkang' 'Yishun' 'Newton'
 'Riverside' 'Punggol' 'Mount Faber' 'West Kowloon' 'Sentosa'
 'Choa Chu Kang' 'Bukit Panjang' 'Tanjong Pagar' 'Clementi' 'Central'
 'Crows Nest' 'Sungei Kadut' 'Little India' 'Rochor' 'Pathum Wan' 'Changi'
 'Downtown Core' 'Keppel Bay' 'Singapore River' 'Outram' 'Museum'
 'Lower Sukhumvit' 'Southern Islands' 'Wan Chai' 'Straits View' 'Tuas']

In [31]:
missing_values_listings = listing_df.isnull().sum()

missing_values_listings[missing_values_listings > 0]

host_acceptance_rate    923
host_is_superhost       189
dtype: int64

In [33]:
listing_df["host_acceptance_rate"].unique()

array(['100%', '95%', nan, '91%', '0%', '80%', '98%', '75%', '88%', '66%',
       '77%', '89%', '49%', '86%', '20%', '50%', '67%', '60%', '22%',
       '84%', '63%', '72%', '62%', '57%', '25%', '70%', '96%', '92%',
       '90%', '93%', '99%', '85%', '21%', '40%', '97%', '71%', '33%',
       '52%', '73%', '58%', '94%', '30%', '26%', '79%', '55%', '82%',
       '46%', '9%', '64%', '6%', '54%', '78%', '53%', '81%', '27%', '61%',
       '87%', '24%'], dtype=object)

In [34]:
# Make host_acceptance_rate numerical and then fill the NaN value
listing_df['host_acceptance_rate'] = listing_df['host_acceptance_rate'].str.rstrip('%').astype('float') / 100.0
listing_df['host_acceptance_rate'].fillna(listing_df['host_acceptance_rate'].mean(), inplace=True)

In [35]:
listing_df["host_is_superhost"].unique()

array(['f', 't', nan], dtype=object)

For `host_is_superhost`, which typically contains categorical values like 't' and 'f', you can fill missing values with the most frequent category.

In [36]:
listing_df['host_is_superhost'].fillna(listing_df['host_is_superhost'].mode()[0], inplace=True)

In [37]:
missing_values_listings = listing_df.isnull().sum()

missing_values_listings[missing_values_listings > 0]

Series([], dtype: int64)

In [38]:
listing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            3483 non-null   int64
 1   listing_url                                   3483 non-null   object
 2   scrape_id                                     3483 non-null   int64
 3   last_scraped                                  3483 non-null   object
 4   source                                        3483 non-null   object
 5   name                                          3483 non-null   object
 6   description                                   3483 non-null   object
 7   neighborhood_overview                         3483 non-null   object
 8   picture_url                                   3483 non-null   object
 9   host_id                                       3483 non-null   int64
 10  host_url                                      3483 non-null   object
 11  host_name                                     3483 non-null   object
 12  host_since                                    3483 non-null   object
 13  host_location                                 3483 non-null   object
 14  host_about                                    3483 non-null   object
 15  host_response_time                            3483 non-null   object
 16  host_response_rate                            3483 non-null   float64
 17  host_acceptance_rate                          3483 non-null   float64
 18  host_is_superhost                             3483 non-null   object
 19  host_thumbnail_url                            3483 non-null   object
 20  host_picture_url                              3483 non-null   object
 21  host_neighbourhood                            3483 non-null   object
 22  host_listings_count                           3483 non-null   int64
 23  host_total_listings_count                     3483 non-null   int64
 24  host_verifications                            3483 non-null   object
 25  host_has_profile_pic                          3483 non-null   object
 26  host_identity_verified                        3483 non-null   object
 27  neighbourhood                                 3483 non-null   object
 28  neighbourhood_cleansed                        3483 non-null   object
 29  neighbourhood_group_cleansed                  3483 non-null   object
 30  latitude                                      3483 non-null   float64
 31  longitude                                     3483 non-null   float64
 32  property_type                                 3483 non-null   object
 33  room_type                                     3483 non-null   object
 34  accommodates                                  3483 non-null   int64
 35  bathrooms_text                                3483 non-null   object
 36  bedrooms                                      3483 non-null   float64
 37  beds                                          3483 non-null   float64
 38  amenities                                     3483 non-null   object
 39  price                                         3483 non-null   object
 40  minimum_nights                                3483 non-null   int64
 41  maximum_nights                                3483 non-null   int64
 42  minimum_minimum_nights                        3483 non-null   int64
 43  maximum_minimum_nights                        3483 non-null   int64
 44  minimum_maximum_nights                        3483 non-null   int64
 45  maximum_maximum_nights                        3483 non-null   int64
 46  minimum_nights_avg_ntm                        3483 non-null   float64
 47  maximum_nights_avg_ntm                        3483 non-null   float64
 48  has_availability                              3483 non-null   object
 49  availability_30                               3483 non-null   int64
 50  availability_60                               3483 non-null   int64
 51  availability_90                               3483 non-null   int64
 52  availability_365                              3483 non-null   int64
 53  calendar_last_scraped                         3483 non-null   object
 54  number_of_reviews                             3483 non-null   int64
 55  number_of_reviews_ltm                         3483 non-null   int64
 56  number_of_reviews_l30d                        3483 non-null   int64
 57  first_review                                  3483 non-null   object
 58  last_review                                   3483 non-null   object
 59  review_scores_rating                          3483 non-null   float64
 60  review_scores_accuracy                        3483 non-null   float64
 61  review_scores_cleanliness                     3483 non-null   float64
 62  review_scores_checkin                         3483 non-null   float64
 63  review_scores_communication                   3483 non-null   float64
 64  review_scores_location                        3483 non-null   float64
 65  review_scores_value                           3483 non-null   float64
 66  instant_bookable                              3483 non-null   object
 67  calculated_host_listings_count                3483 non-null   int64
 68  calculated_host_listings_count_entire_homes   3483 non-null   int64
 69  calculated_host_listings_count_private_rooms  3483 non-null   int64
 70  calculated_host_listings_count_shared_rooms   3483 non-null   int64
 71  reviews_per_month                             3483 non-null   float64
dtypes: float64(16), int64(23), object(33)
memory usage: 1.9+ MB

Downcasting numerical columns and converting object columns to categorical types can significantly reduce memory usage, especially for large datasets.

In [39]:
# Display the data types of columns before changes
print("Data types before changes:")
print(listing_df.dtypes)

# Measure memory usage before changes
memory_before = listing_df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nMemory usage before changes: {memory_before:.2f} MB\n")

# Convert columns to appropriate data types
# Convert numerical columns to more memory-efficient types
numerical_columns = listing_df.select_dtypes(include=['float64', 'int64']).columns
listing_df[numerical_columns] = listing_df[numerical_columns].apply(pd.to_numeric, downcast='float')

# Convert object columns to categorical if appropriate
object_columns = listing_df.select_dtypes(include='object').columns
listing_df[object_columns] = listing_df[object_columns].astype('category')

# Display the data types of columns after changes
print("Data types after changes:")
print(listing_df.dtypes)

# Measure memory usage after changes
memory_after = listing_df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nMemory usage after changes: {memory_after:.2f} MB\n")

# Calculate memory savings
memory_savings = (1 - memory_after / memory_before) * 100
print(f"Memory savings: {memory_savings:.2f}%")

Data types before changes:
id                                                int64
listing_url                                      object
scrape_id                                         int64
last_scraped                                     object
source                                           object
                                                 ...
calculated_host_listings_count                    int64
calculated_host_listings_count_entire_homes       int64
calculated_host_listings_count_private_rooms      int64
calculated_host_listings_count_shared_rooms       int64
reviews_per_month                               float64
Length: 72, dtype: object

Memory usage before changes: 17.04 MB

Data types after changes:
id                                               float64
listing_url                                     category
scrape_id                                        float64
last_scraped                                    category
source                                          category
                                                  ...
calculated_host_listings_count                   float32
calculated_host_listings_count_entire_homes      float32
calculated_host_listings_count_private_rooms     float32
calculated_host_listings_count_shared_rooms      float32
reviews_per_month                                float32
Length: 72, dtype: object

Memory usage after changes: 9.16 MB

Memory savings: 46.23%

In [40]:
listing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3483 entries, 0 to 3482
Data columns (total 72 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            3483 non-null   float64
 1   listing_url                                   3483 non-null   category
 2   scrape_id                                     3483 non-null   float64
 3   last_scraped                                  3483 non-null   category
 4   source                                        3483 non-null   category
 5   name                                          3483 non-null   category
 6   description                                   3483 non-null   category
 7   neighborhood_overview                         3483 non-null   category
 8   picture_url                                   3483 non-null   category
 9   host_id                                       3483 non-null   float64
 10  host_url                                      3483 non-null   category
 11  host_name                                     3483 non-null   category
 12  host_since                                    3483 non-null   category
 13  host_location                                 3483 non-null   category
 14  host_about                                    3483 non-null   category
 15  host_response_time                            3483 non-null   category
 16  host_response_rate                            3483 non-null   float32
 17  host_acceptance_rate                          3483 non-null   float32
 18  host_is_superhost                             3483 non-null   category
 19  host_thumbnail_url                            3483 non-null   category
 20  host_picture_url                              3483 non-null   category
 21  host_neighbourhood                            3483 non-null   category
 22  host_listings_count                           3483 non-null   float32
 23  host_total_listings_count                     3483 non-null   float32
 24  host_verifications                            3483 non-null   category
 25  host_has_profile_pic                          3483 non-null   category
 26  host_identity_verified                        3483 non-null   category
 27  neighbourhood                                 3483 non-null   category
 28  neighbourhood_cleansed                        3483 non-null   category
 29  neighbourhood_group_cleansed                  3483 non-null   category
 30  latitude                                      3483 non-null   float32
 31  longitude                                     3483 non-null   float32
 32  property_type                                 3483 non-null   category
 33  room_type                                     3483 non-null   category
 34  accommodates                                  3483 non-null   float32
 35  bathrooms_text                                3483 non-null   category
 36  bedrooms                                      3483 non-null   float32
 37  beds                                          3483 non-null   float32
 38  amenities                                     3483 non-null   category
 39  price                                         3483 non-null   category
 40  minimum_nights                                3483 non-null   float32
 41  maximum_nights                                3483 non-null   float32
 42  minimum_minimum_nights                        3483 non-null   float32
 43  maximum_minimum_nights                        3483 non-null   float32
 44  minimum_maximum_nights                        3483 non-null   float32
 45  maximum_maximum_nights                        3483 non-null   float32
 46  minimum_nights_avg_ntm                        3483 non-null   float32
 47  maximum_nights_avg_ntm                        3483 non-null   float32
 48  has_availability                              3483 non-null   category
 49  availability_30                               3483 non-null   float32
 50  availability_60                               3483 non-null   float32
 51  availability_90                               3483 non-null   float32
 52  availability_365                              3483 non-null   float32
 53  calendar_last_scraped                         3483 non-null   category
 54  number_of_reviews                             3483 non-null   float32
 55  number_of_reviews_ltm                         3483 non-null   float32
 56  number_of_reviews_l30d                        3483 non-null   float32
 57  first_review                                  3483 non-null   category
 58  last_review                                   3483 non-null   category
 59  review_scores_rating                          3483 non-null   float32
 60  review_scores_accuracy                        3483 non-null   float32
 61  review_scores_cleanliness                     3483 non-null   float32
 62  review_scores_checkin                         3483 non-null   float32
 63  review_scores_communication                   3483 non-null   float32
 64  review_scores_location                        3483 non-null   float32
 65  review_scores_value                           3483 non-null   float32
 66  instant_bookable                              3483 non-null   category
 67  calculated_host_listings_count                3483 non-null   float32
 68  calculated_host_listings_count_entire_homes   3483 non-null   float32
 69  calculated_host_listings_count_private_rooms  3483 non-null   float32
 70  calculated_host_listings_count_shared_rooms   3483 non-null   float32
 71  reviews_per_month                             3483 non-null   float32
dtypes: category(33), float32(36), float64(3)
memory usage: 1.6 MB

### Do the cleaning for reviews

In [41]:
# Identify the missing data on the listing_df
missing_values_listings = review_df.isnull().sum()

missing_values_listings[missing_values_listings > 0]

comments    7
dtype: int64

In [42]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35698 entries, 0 to 35697
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     35698 non-null  int64
 1   id             35698 non-null  int64
 2   date           35698 non-null  object
 3   reviewer_id    35698 non-null  int64
 4   reviewer_name  35698 non-null  object
 5   comments       35691 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.6+ MB

In [45]:
review_df['comments'].fillna('Not available', inplace=True)

In [46]:
review_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35698 entries, 0 to 35697
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   listing_id     35698 non-null  int64
 1   id             35698 non-null  int64
 2   date           35698 non-null  object
 3   reviewer_id    35698 non-null  int64
 4   reviewer_name  35698 non-null  object
 5   comments       35698 non-null  object
dtypes: int64(3), object(3)
memory usage: 1.6+ MB

In [47]:
# Display the data types of columns before changes
print("Data types before changes:")
print(review_df.dtypes)

# Measure memory usage before changes
memory_before = review_df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nMemory usage before changes: {memory_before:.2f} MB\n")

# Convert columns to appropriate data types
# Example: Convert numerical columns to more memory-efficient types
numerical_columns = review_df.select_dtypes(include=['int64']).columns
review_df[numerical_columns] = review_df[numerical_columns].apply(pd.to_numeric, downcast='integer')

# Example: Convert object columns to categorical if appropriate
object_columns = review_df.select_dtypes(include='object').columns
review_df[object_columns] = review_df[object_columns].astype('category')

# Display the data types of columns after changes
print("Data types after changes:")
print(review_df.dtypes)

# Measure memory usage after changes
memory_after = review_df.memory_usage(deep=True).sum() / (1024 ** 2)
print(f"\nMemory usage after changes: {memory_after:.2f} MB\n")

# Calculate memory savings
memory_savings = (1 - memory_after / memory_before) * 100
print(f"Memory savings: {memory_savings:.2f}%")

Data types before changes:
listing_id        int64
id                int64
date             object
reviewer_id       int64
reviewer_name    object
comments         object
dtype: object

Memory usage before changes: 16.64 MB

Data types after changes:
listing_id          int64
id                  int64
date             category
reviewer_id         int32
reviewer_name    category
comments         category
dtype: object

Memory usage after changes: 17.49 MB

Memory savings: -5.11%